// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { existsSync } from "node:fs";
import path from "node:path";
import { defineConfig } from "prisma/config";

const localSchemaEnginePath = path.resolve(
  "node_modules",
  "@prisma",
  "engines",
  "schema-engine-windows.exe",
);

if (
  process.platform === "win32" &&
  !process.env.PRISMA_SCHEMA_ENGINE_BINARY &&
  existsSync(localSchemaEnginePath)
) {
  process.env.PRISMA_SCHEMA_ENGINE_BINARY = localSchemaEnginePath;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
